// src/components/analysis/ExportResults.tsx

"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Download,
  Share2,
  Copy,
  Check,
  FileText,
  Printer,
  X,
  Mail,
} from "lucide-react";
import toast from "react-hot-toast";

interface AnalysisData {
  symptoms: string[];
  severity: string;
  conditions: Array<{ name: string; probability: number; description: string }>;
  recommendations: string[];
  remedies: Array<{ name: string; description: string }>;
  warningFlags: string[];
  date: string;
}

interface ExportResultsProps {
  data: AnalysisData;
}

export function ExportResults({ data }: ExportResultsProps) {
  const [showModal, setShowModal] = useState(false);
  const [copied, setCopied] = useState(false);

  // Generate text summary
  const generateTextSummary = () => {
    const lines = [
      "═══════════════════════════════════════",
      "       MEDASSIST HEALTH ANALYSIS",
      "═══════════════════════════════════════",
      "",
      `Date: ${new Date(data.date).toLocaleDateString()}`,
      `Severity: ${data.severity.toUpperCase()}`,
      "",
      "───────────────────────────────────────",
      "SYMPTOMS ANALYZED",
      "───────────────────────────────────────",
      ...data.symptoms.map((s) => `• ${s}`),
      "",
    ];

    if (data.conditions.length > 0) {
      lines.push(
        "───────────────────────────────────────",
        "POSSIBLE CONDITIONS",
        "───────────────────────────────────────",
        ...data.conditions.map(
          (c) => `• ${c.name} (${Math.round(c.probability * 100)}% match)\n  ${c.description}`
        ),
        ""
      );
    }

    if (data.recommendations.length > 0) {
      lines.push(
        "───────────────────────────────────────",
        "RECOMMENDATIONS",
        "───────────────────────────────────────",
        ...data.recommendations.map((r) => `• ${r}`),
        ""
      );
    }

    if (data.remedies.length > 0) {
      lines.push(
        "───────────────────────────────────────",
        "SUGGESTED REMEDIES",
        "───────────────────────────────────────",
        ...data.remedies.map((r) => `• ${r.name}\n  ${r.description}`),
        ""
      );
    }

    if (data.warningFlags.length > 0) {
      lines.push(
        "───────────────────────────────────────",
        "⚠️ WARNINGS",
        "───────────────────────────────────────",
        ...data.warningFlags.map((w) => `• ${w}`),
        ""
      );
    }

    lines.push(
      "═══════════════════════════════════════",
      "DISCLAIMER: This analysis is for informational",
      "purposes only. Please consult a healthcare",
      "professional for proper diagnosis and treatment.",
      "═══════════════════════════════════════",
      "",
      "Generated by MedAssist - medassist.app"
    );

    return lines.join("\n");
  };

  // Generate HTML for printing
  const generateHTML = () => {
    return `
<!DOCTYPE html>
<html>
<head>
  <title>MedAssist Analysis Report</title>
  <style>
    body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; color: #333; }
    h1 { color: #452829; border-bottom: 2px solid #E8D1C5; padding-bottom: 10px; }
    h2 { color: #452829; margin-top: 30px; }
    .meta { color: #666; margin-bottom: 30px; }
    .severity { display: inline-block; padding: 5px 15px; border-radius: 20px; font-weight: bold; }
    .severity.low { background: #dcfce7; color: #166534; }
    .severity.moderate { background: #fef9c3; color: #854d0e; }
    .severity.high { background: #fee2e2; color: #991b1b; }
    ul { padding-left: 20px; }
    li { margin: 8px 0; }
    .warning { background: #fee2e2; border: 1px solid #fca5a5; padding: 15px; border-radius: 8px; margin: 20px 0; }
    .disclaimer { background: #f3f4f6; padding: 15px; border-radius: 8px; margin-top: 30px; font-size: 14px; color: #666; }
    .footer { margin-top: 40px; text-align: center; color: #999; font-size: 12px; }
  </style>
</head>
<body>
  <h1>🏥 MedAssist Health Analysis</h1>
  <div class="meta">
    <p><strong>Date:</strong> ${new Date(data.date).toLocaleDateString()}</p>
    <p><strong>Severity:</strong> <span class="severity ${data.severity}">${data.severity.toUpperCase()}</span></p>
  </div>

  <h2>📋 Symptoms Analyzed</h2>
  <ul>
    ${data.symptoms.map((s) => `<li>${s}</li>`).join("")}
  </ul>

  ${
    data.conditions.length > 0
      ? `
  <h2>🔍 Possible Conditions</h2>
  <ul>
    ${data.conditions.map((c) => `<li><strong>${c.name}</strong> (${Math.round(c.probability * 100)}% match)<br><small>${c.description}</small></li>`).join("")}
  </ul>
  `
      : ""
  }

  ${
    data.recommendations.length > 0
      ? `
  <h2>💡 Recommendations</h2>
  <ul>
    ${data.recommendations.map((r) => `<li>${r}</li>`).join("")}
  </ul>
  `
      : ""
  }

  ${
    data.remedies.length > 0
      ? `
  <h2>🌿 Suggested Remedies</h2>
  <ul>
    ${data.remedies.map((r) => `<li><strong>${r.name}</strong><br><small>${r.description}</small></li>`).join("")}
  </ul>
  `
      : ""
  }

  ${
    data.warningFlags.length > 0
      ? `
  <div class="warning">
    <h3>⚠️ Important Warnings</h3>
    <ul>
      ${data.warningFlags.map((w) => `<li>${w}</li>`).join("")}
    </ul>
  </div>
  `
      : ""
  }

  <div class="disclaimer">
    <strong>Disclaimer:</strong> This analysis is for informational purposes only and is not a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified health provider.
  </div>

  <div class="footer">
    Generated by MedAssist | ${new Date().toLocaleDateString()}
  </div>
</body>
</html>
    `;
  };

  // Copy to clipboard
  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(generateTextSummary());
      setCopied(true);
      toast.success("Copied to clipboard!");
      setTimeout(() => setCopied(false), 2000);
    } catch (error) {
      toast.error("Failed to copy");
    }
  };

  // Download as text file
  const handleDownloadText = () => {
    const blob = new Blob([generateTextSummary()], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `medassist-analysis-${new Date().toISOString().split("T")[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success("Downloaded!");
  };

  // Print
  const handlePrint = () => {
    const printWindow = window.open("", "_blank");
    if (printWindow) {
      printWindow.document.write(generateHTML());
      printWindow.document.close();
      printWindow.print();
    }
  };

  // Share via email
  const handleEmail = () => {
    const subject = encodeURIComponent("MedAssist Health Analysis Report");
    const body = encodeURIComponent(generateTextSummary());
    window.location.href = `mailto:?subject=${subject}&body=${body}`;
  };

  // Native share (mobile)
  const handleNativeShare = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: "MedAssist Health Analysis",
          text: generateTextSummary(),
        });
      } catch (error) {
        // User cancelled or error
      }
    } else {
      setShowModal(true);
    }
  };

  return (
    <>
      {/* Export Button */}
      <button
        onClick={() => setShowModal(true)}
        style={{
          display: "flex",
          alignItems: "center",
          gap: "8px",
          padding: "12px 20px",
          background: "var(--bg-tertiary)",
          border: "1px solid var(--border-light)",
          borderRadius: "10px",
          fontSize: "14px",
          fontWeight: 500,
          color: "var(--text-secondary)",
          cursor: "pointer",
          transition: "all 0.2s ease",
        }}
      >
        <Share2 size={18} />
        Export / Share
      </button>

      {/* Modal */}
      <AnimatePresence>
        {showModal && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            style={{
              position: "fixed",
              inset: 0,
              background: "rgba(0,0,0,0.5)",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              padding: "20px",
              zIndex: 100,
            }}
            onClick={() => setShowModal(false)}
          >
            <motion.div
              initial={{ scale: 0.95, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.95, opacity: 0 }}
              onClick={(e) => e.stopPropagation()}
              style={{
                background: "var(--bg-tertiary)",
                borderRadius: "20px",
                padding: "28px",
                width: "100%",
                maxWidth: "400px",
              }}
            >
              {/* Header */}
              <div
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "center",
                  marginBottom: "24px",
                }}
              >
                <h3 style={{ fontSize: "18px", fontWeight: 600 }}>Export & Share</h3>
                <button
                  onClick={() => setShowModal(false)}
                  style={{
                    width: "36px",
                    height: "36px",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    background: "var(--bg-secondary)",
                    border: "none",
                    borderRadius: "10px",
                    cursor: "pointer",
                  }}
                >
                  <X size={18} />
                </button>
              </div>

              {/* Options */}
              <div style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
                {/* Copy */}
                <button
                  onClick={handleCopy}
                  style={{
                    display: "flex",
                    alignItems: "center",
                    gap: "12px",
                    padding: "16px",
                    background: "var(--bg-secondary)",
                    border: "1px solid var(--border-light)",
                    borderRadius: "12px",
                    cursor: "pointer",
                    width: "100%",
                    textAlign: "left",
                  }}
                >
                  {copied ? (
                    <Check size={20} style={{ color: "var(--success)" }} />
                  ) : (
                    <Copy size={20} style={{ color: "var(--text-secondary)" }} />
                  )}
                  <div>
                    <p style={{ fontWeight: 500, fontSize: "15px", marginBottom: "2px" }}>
                      {copied ? "Copied!" : "Copy to Clipboard"}
                    </p>
                    <p style={{ fontSize: "13px", color: "var(--text-muted)" }}>
                      Copy analysis as text
                    </p>
                  </div>
                </button>

                {/* Download */}
                <button
                  onClick={handleDownloadText}
                  style={{
                    display: "flex",
                    alignItems: "center",
                    gap: "12px",
                    padding: "16px",
                    background: "var(--bg-secondary)",
                    border: "1px solid var(--border-light)",
                    borderRadius: "12px",
                    cursor: "pointer",
                    width: "100%",
                    textAlign: "left",
                  }}
                >
                  <Download size={20} style={{ color: "var(--text-secondary)" }} />
                  <div>
                    <p style={{ fontWeight: 500, fontSize: "15px", marginBottom: "2px" }}>
                      Download
                    </p>
                    <p style={{ fontSize: "13px", color: "var(--text-muted)" }}>
                      Save as text file
                    </p>
                  </div>
                </button>

                {/* Print */}
                <button
                  onClick={handlePrint}
                  style={{
                    display: "flex",
                    alignItems: "center",
                    gap: "12px",
                    padding: "16px",
                    background: "var(--bg-secondary)",
                    border: "1px solid var(--border-light)",
                    borderRadius: "12px",
                    cursor: "pointer",
                    width: "100%",
                    textAlign: "left",
                  }}
                >
                  <Printer size={20} style={{ color: "var(--text-secondary)" }} />
                  <div>
                    <p style={{ fontWeight: 500, fontSize: "15px", marginBottom: "2px" }}>
                      Print
                    </p>
                    <p style={{ fontSize: "13px", color: "var(--text-muted)" }}>
                      Print formatted report
                    </p>
                  </div>
                </button>

                {/* Email */}
                <button
                  onClick={handleEmail}
                  style={{
                    display: "flex",
                    alignItems: "center",
                    gap: "12px",
                    padding: "16px",
                    background: "var(--bg-secondary)",
                    border: "1px solid var(--border-light)",
                    borderRadius: "12px",
                    cursor: "pointer",
                    width: "100%",
                    textAlign: "left",
                  }}
                >
                  <Mail size={20} style={{ color: "var(--text-secondary)" }} />
                  <div>
                    <p style={{ fontWeight: 500, fontSize: "15px", marginBottom: "2px" }}>
                      Send via Email
                    </p>
                    <p style={{ fontSize: "13px", color: "var(--text-muted)" }}>
                      Open in email client
                    </p>
                  </div>
                </button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  );
}